---
#broker: 'amqp://guest:guest@localhost:5672/'
broker: 'redis://0.0.0.0:32772'
#broker: 'https://sqs.us-west-2.amazonaws.com/123456789012'
default_queue: machinery_tasks

result_backend: 'redis://0.0.0.0:32772'
#result_backend: 'memcache://localhost:11211'
#result_backend: 'mongodb://localhost:27017'
results_expire_in: 3600000